# Generated by Django 4.2.1 on 2023-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fieldA', models.TextField()),
                ('fieldB', models.IntegerField()),
                ('fieldC', models.EmailField(max_length=254)),
                ('createdBy', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
